export default {
  user1: {
    name: 'John Doe',
    username: 'johnd',
    email: 'johnd@email.com',
    imgUrl: '',
    password: 'Aa!12345',
    confirmPassword: 'Aa!12345',
    wrongPassword: 'Aaa12345',
    isAdmin: true,
  },
  user2: {
    name: 'ryan brain',
    username: 'ryanb',
    email: 'ryanb@email.com',
    imgUrl: '',
    password: 'Aa!12345',
    confirmPassword: 'Aa!12345',
    wrongPassword: 'Aaa12345',
    isAdmin: false,
  },
  editUser1: {
    name: 'John Doe edit',
    username: 'johnde',
    email: 'johnde@email.com',
    imgUrl: '',
    password: 'Aa!12345',
    confirmPassword: 'Aa!12345',
    wrongPassword: 'Aaa12345',
    isAdmin: true,
  },
  editUser2: {
    name: 'ryan brain',
    username: 'ryanb',
    email: 'ryanb@email.com',
    imgUrl: '/',
    password: 'Aa!12345',
    confirmPassword: 'Aa!12345',
    wrongPassword: 'Aaa12345',
    isAdmin: false,
  },
  wrongUser1: {
    username: 'unknown',
    password: 'a1234sda',
  },
  wrongUser2: {
    username: 'username',
    password: 'fd5328r75saa?',
  },
};
